### ISSUE TITLE
搜索功能无法加载bug

### ISSUE THREAD

**Issue by xiyuvi** [isooosi/VisVrs#10]
![image](https://github.com/isooosi/VisVrs/assets/38217058/b4e1b89e-94cc-464a-86e5-c4eee66a0196)
只要先点击某个页面的链接,再点击搜索一定出现白屏. f5刷新页面后,搜索功能才能正常

**Comment by isooosi** [comment]
This issue is caused by the built-in [**View Transitions**](https://docs.astro.build/en/guides/view-transitions/) feature in Astro. You can resolve it by enabling `transition:persist`.

Alternatively, if you don't require the View Transitions functionality, you can remove the relevant code in `src/layouts/BaseLayout.astro`.
